#ifndef _SETTINGS_
#define _SETTINGS_

#define PARSER_MAX_DATAPRIMITIVES 55
#define PARSER_DEFAULT_DATAPRIMITIVES_COUNT 20
#define OPCODE_DATAPRIMITIVES_BEGIN 200

#define PARSER_OPCODE_TYPE unsigned char
#define DEFAULT_OPCODE_COUNT 100

// 0-25 a-z
// 26-35 A-Z
// 36-45 0-9
// 46 _
#define PARSER_SYMBOL_CHAR_COUNT 47
#define PARSER_MAX_SYMBOLS 200

#endif
